### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-1#1]
Let's make a simple blog.

Technologies:
- Node.js
- Express
- PostgreSQL
- Knex or pg
- pug

For the first step we need only one table `posts`. We need such endoints:
 - / -- list of posts
- /new -- a form for post creation

Post should have such fields:
- id
- createdAt
- title
- description
- tags (list of strings, for example: ["node", "react"]

**Comment by serge-nikitin** [comment]
For the first version let's use only callback style. So, no promises, no async await.

**Comment by serge-nikitin** [comment]
Please, don't copy-paste code again.

const cookieParser = require('cookie-parser'); -- you don't need cookie-parser.


```
// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

```

This is not your code too.

**Comment by marcpre** [comment]
Jup will remove it. I am going to create a learning repo for `morgan`, `body-parser` and `cookie-parser`.

I  played today with callbacks (see f.ex.: [callback example](https://github.com/marcpre/learning_js/blob/master/t01-callback.js))

Is there a way to run both synchronous and asynchronous code, in the callback way, together without making inserting callback function by callback function?

**Comment by marcpre** [comment]
Please see the current version of the implementation.

In the Service Layer I used the following implentation:

```
function getAllPosts(callback) {
    knex('posts').select().where({
        deleted: false,
    }).orderBy('createdAt').asCallback(function(err, res){
        if(err) console.log(err)
        callback(res)
    })
}
```

For the `getAllPosts` I used `asCallback` as knex gives back a promise.

```
function createPost(titel, description, tags, callback) {

    let post = {
        titel: titel,
        description: description,
        tags: tags,
        createdAt: new Date(),
        deleted: false
    }

    knex('posts').insert(post, 'id').then(id => {
        console.log(id)
        callback(id[0])
    })
}
```

For the `createPost ` method I used `then`, however I am returing a `callback`.

Appreciate your comments on my code.

Thanks in advance!

**Comment by serge-nikitin** [comment]
In general everything is OK.
