### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-1#2]
Let's show 10 posts by page only. So we need to add pagination.

**Comment by marcpre** [comment]
Hello,

I am thinking about implementing this either by passing an argument directly to the database query or using this node package [express-paginate](https://github.com/expressjs/express-paginate).

From your point of view, what would be the recommend way to go here?

**Comment by serge-nikitin** [comment]
It's better to implement pagination without any additional libraries.

**Comment by serge-nikitin** [comment]
from this library documentation:

> Node.js pagination middleware and view helpers. To be used in combination with database pagination plugins such as mongoose-paginate.

You don't use MongoDB, but PostgreSQL.

**Comment by marcpre** [comment]
I added pagination to the table using the Pug Template Engine.

I think in react or vue creating such "datatables" can be done much easier and better. Need to start learning this...
